### ISSUE TITLE
여행 계획 View

### ISSUE THREAD

**Issue by dhflxhdxhd** [D-Nolja/Frontend#14]
## Description ✏
- 여행 계획 짜는 페이지를 만들어볼게?

## Todo 📝
- [x] side-menu 구조 
- [x] side-menu drag event 
-- drag 했을 때 펴지게
-- day 3개까지 펴지게
-- 이후 day들의 경우 스크롤 가능
- [x] side-nav & side-menu 배치

## ETC 📌
- 화이팅....
