### ISSUE TITLE
메인페이지를 만들어보자

### ISSUE THREAD

**Issue by dhflxhdxhd** [D-Nolja/Frontend#32]
## Description ✏
- 메인페이지 구성 및 style

## Todo 📝
- [x] hero component 
- [x] card1 component
- [x] 전체 구조 및 스타일
- [x] hero btn 라우터 연결
- [x] scroll에 따른 애니메이션도 넣어야 해!

## ETC 📌
- 메인은 진짜 난감

**Comment by dhflxhdxhd** [comment]
메인 종료
