### ISSUE TITLE
시설 조회 기능 구현

### ISSUE THREAD

**Issue by dhflxhdxhd** [D-Nolja/Frontend#44]
## Description ✏
- 시설 조회 후 place 상태를 pinia로 관리해보자

## Todo 📝
- [ ] 시설조회 - 전체
- [ ] 시설조회 - 검색어
- [ ] 시설조회 - 카테고리
- [ ] 시설조회 - 검색어 + 카테고리
- [ ] 시설조회 - 카테고리 + 최단 거리
- [ ] 시설조회 - 검색어 + 타입 + 최단 거리
- [ ] 시설조회 - 현재 위치 기준 최단 거리 (페이지네이션 X or 1)
- [ ]
