### ISSUE TITLE
장소 검색 분기

### ISSUE THREAD

**Issue by dhflxhdxhd** [D-Nolja/Frontend#57]
## Description ✏
- 장소검색에 필요한 애들 구조화 

## Todo 📝
- [x] searchParam 값 입력, 초기화
- [x] searchParam에 따른 검색 분기
- [x] 검색 파일 분리...?해야할까?
